server:
  port: 8887
spring:
  application:
    name: service-b
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: cfg-server
eureka:
  client:
    #发现服务
    fetch-registry: true
    #注册服务
    register-with-eureka: true
    #服务注册中心地址
    service-url:
      defaultZone: http://localhost:8881/eureka/
