server:
  port: 8888
spring:
  application:
    name: cfg-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cheerUpPing/myspringcloudconfigserver
          search-paths: config
          username: cheerUpPing
          password: xx6471952xx
      label: master
#向服务注册中心注册配置服务器
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8881/eureka/